# Generated by Django 5.1.6 on 2026-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='total_xp',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
