# Generated by Django 5.1.6 on 2026-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_xp_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text="Set only when avatar_source is 'upload'.", null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avatar_source',
            field=models.CharField(choices=[('monogram', 'Monogram'), ('upload', 'Uploaded image'), ('preset', 'Equipped preset')], default='monogram', max_length=10),
        ),
    ]
