# Generated by Django 5.1.6 on 2026-03-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='answers',
            field=models.JSONField(default=dict, help_text='Submitted answers: {index: {answer, is_correct, exercise_id}}'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='exercise_instances',
            field=models.JSONField(default=list, help_text='Generated exercise instances for this attempt'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=15),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final score percentage, set on completion', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
