# Generated by Django 5.1.6 on 2026-03-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_categoryprogress_session_id'),
        ('progress', '0003_testattempt_status_instances'),
    ]

    operations = [
    ]
