# Generated by Django 5.1.6 on 2026-03-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_merge_20260317_1252'),
        ('progress', '0005_categoryprogress_topic'),
    ]

    operations = [
    ]
