# Generated by Django 5.1.6 on 2026-04-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_merge_20260321_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprogress',
            name='category_failure_count',
            field=models.PositiveIntegerField(default=0, help_text='First-wrong-in-batch counter per category. Resets when hint is used.'),
        ),
        migrations.AddField(
            model_name='categoryprogress',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last counted failure. Used for 7-day sliding window reset.', null=True),
        ),
        migrations.AlterField(
            model_name='categoryprogress',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classroompace',
            name='unlock_date',
            field=models.DateField(),
        ),
    ]
