# Generated by Django 5.1.6 on 2026-04-17 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_categoryprogress_hint_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='freeze_count',
            field=models.PositiveIntegerField(default=0, help_text='Stockpiled streak freezes. Max 2. Earned 1 per 7 consecutive active days.'),
        ),
        migrations.CreateModel(
            name='StreakActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity_type', models.CharField(choices=[('exercise', 'Exercise'), ('lesson', 'Lesson'), ('topic_test', 'Topic Test'), ('unit_test', 'Unit Test'), ('daily_test', 'Daily Test')], max_length=20)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='streak_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'streak_activities',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
