# Generated by Django 5.1.6 on 2026-04-18 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_streak_freeze_count_streakactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exercise_instances', models.JSONField(default=list)),
                ('completed_indices', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_test_sessions',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
