# Generated by Django 5.1.6 on 2026-04-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_dailytestsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytestsession',
            name='answers',
            field=models.JSONField(default=dict, help_text='Submitted answers for completed slots: {"0": student_answer, ...}'),
        ),
    ]
