# Generated by Django 5.1.6 on 2026-05-10 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_lesson_options_remove_glossaryterm_lesson_and_more'),
        ('progress', '0012_achievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XPLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, help_text="Slug from XP_AWARDS (e.g. 'topic_passed').", max_length=64)),
                ('amount', models.IntegerField()),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(help_text='Grade context the grant was earned in. Drives per-grade leaderboards.', on_delete=django.db.models.deletion.PROTECT, related_name='xp_grants', to='content.grade')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='xp_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xp_ledger',
                'ordering': ['-granted_at'],
                'unique_together': {('student', 'idempotency_key')},
            },
        ),
    ]
