# Generated by Django 5.1.6 on 2026-05-18 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0013_xp_foundation'),
        ('users', '0002_xp_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Europe/Bucharest local date.')),
                ('points', models.PositiveIntegerField(default=0)),
                ('claimed_thresholds', models.JSONField(default=list, help_text='Claimed DAILY_MILESTONES thresholds, e.g. [20, 60]. Unordered set.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_progress', to='users.studentprofile')),
            ],
            options={
                'db_table': 'daily_challenge_progress',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QuestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_slug', models.CharField(help_text='Slug from QUEST_CATALOG. Free-form: catalog edits need no migration.', max_length=64)),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=8)),
                ('period_key', models.CharField(help_text='Bucharest-local ISO date (daily) or ISO year+week (weekly).', max_length=16)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('target', models.PositiveIntegerField(help_text='target_count snapshotted from the catalog at creation.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('claimed', 'Claimed'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_assignments', to='users.studentprofile')),
            ],
            options={
                'db_table': 'quest_assignments',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'quest_slug', 'period_key')},
            },
        ),
    ]
