# Generated by Django 5.1.6 on 2026-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0014_quests_foundation'),
        ('users', '0002_xp_foundation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='questassignment',
            index=models.Index(fields=['student', 'cadence', 'period_key'], name='quest_student_period_idx'),
        ),
    ]
