# Generated by Django 5.1.6 on 2026-05-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0015_quest_period_index'),
        ('users', '0003_studentprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosmetic_slug', models.CharField(help_text='Slug from COSMETIC_CATALOG. Free-form: catalog edits need no migration.', max_length=64)),
                ('cosmetic_type', models.CharField(choices=[('frame', 'Frame'), ('profile_theme', 'Profile Theme'), ('avatar', 'Avatar')], help_text='type snapshotted from the catalog at creation; drives the one-equipped-per-type constraint.', max_length=16)),
                ('is_equipped', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to='users.studentprofile')),
            ],
            options={
                'db_table': 'student_cosmetics',
                'ordering': ['-unlocked_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'cosmetic_slug'), name='uniq_student_cosmetic'), models.UniqueConstraint(condition=models.Q(('is_equipped', True)), fields=('student', 'cosmetic_type'), name='uniq_one_equipped_per_type')],
            },
        ),
    ]
