# Generated by Django 5.1.6 on 2026-02-15 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Rich text with KaTeX math notation')),
                ('is_published', models.BooleanField(default=False)),
                ('practice_minimum', models.PositiveSmallIntegerField(default=5, help_text='Exercises to complete before next lesson unlocks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['unit', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('expression', 'Expression Input'), ('true_false', 'True/False')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('template', models.JSONField(help_text='JSONB template: params, answer formula, validation rules, display text')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='content.lesson')),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('recommended_unlock_date', models.DateField(blank=True, help_text='Default earliest date this unit becomes available', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='content.grade')),
            ],
            options={
                'db_table': 'units',
                'ordering': ['grade', 'order'],
                'unique_together': {('grade', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_threshold', models.PositiveSmallIntegerField(default=70, help_text='Minimum score (%) to pass')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Time limit in minutes. Null = untimed.', null=True)),
                ('exercise_count', models.PositiveSmallIntegerField(default=10, help_text='Number of exercises in this test')),
                ('retry_practice_count', models.PositiveSmallIntegerField(default=5, help_text='Extra practice exercises required after a failed attempt')),
                ('is_published', models.BooleanField(default=False)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='content.unit')),
            ],
            options={
                'db_table': 'tests',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('unit', 'order')},
        ),
    ]
