# Generated by Django 5.1.6 on 2026-03-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_lesson_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('expression', 'Expression Input'), ('true_false', 'True/False'), ('drag_order', 'Drag to Order'), ('click_select', 'Click to Select')], max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='blocks',
            field=models.JSONField(blank=True, default=list, help_text='Structured lesson content as an array of typed blocks. See BLOCK_SCHEMA.md for the full specification.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='practice_minimum',
            field=models.PositiveSmallIntegerField(default=5, help_text='Minimum exercises to complete before next lesson unlocks'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True, help_text='Short description shown in lesson lists and cards'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='recommended_unlock_date',
            field=models.DateField(blank=True, help_text='Default earliest date this unit should unlock for students', null=True),
        ),
    ]
