# Generated by Django 5.1.6 on 2026-03-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_exercise_exercise_type_alter_grade_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('expression', 'Expression Input'), ('true_false', 'True/False'), ('drag_order', 'Drag to Order'), ('click_select', 'Click to Select'), ('comparison', 'Comparison (<, =, >)')], max_length=20),
        ),
    ]
