# Generated by Django 5.1.6 on 2026-03-16 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_exercise_exercise_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='exercise_count',
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, default='', help_text="Math exercise category e.g. 'expanded_form', 'digit_identification'", max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='composition',
            field=models.JSONField(default=list, help_text='List of {category, count, weight, difficulty} dicts. Example: [{"category": "expanded_form", "count": 2, "weight": 30, "difficulty": "easy"}]'),
        ),
        migrations.AddField(
            model_name='test',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='test',
            name='scope',
            field=models.CharField(choices=[('lesson', 'Lesson Test'), ('unit', 'Unit Test')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='pass_threshold',
            field=models.PositiveSmallIntegerField(default=60, help_text='Minimum score (%) to pass'),
        ),
        migrations.AlterField(
            model_name='test',
            name='retry_practice_count',
            field=models.PositiveSmallIntegerField(default=5, help_text='Extra practice exercises required after a failed attempt before retry'),
        ),
        migrations.AlterField(
            model_name='test',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='content.unit'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lesson__isnull', False), ('scope', 'lesson'), ('unit__isnull', True)), models.Q(('lesson__isnull', True), ('scope', 'unit'), ('unit__isnull', False)), _connector='OR'), name='test_scope_consistency'),
        ),
    ]
