# Generated by Django 5.1.6 on 2026-05-01 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['topic', 'order']},
        ),
        migrations.RemoveField(
            model_name='glossaryterm',
            name='lesson',
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text='Inflected forms / synonyms used for matching, e.g. ["numere", "numărul"]'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='category',
            field=models.CharField(choices=[('definition', 'Definiție'), ('notation', 'Notație'), ('property', 'Proprietate'), ('other', 'Altele')], default='definition', max_length=20),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='examples',
            field=models.JSONField(blank=True, default=list, help_text='Example strings; KaTeX inline $...$ allowed.'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='term',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='glossary_terms', to='content.unit'),
        ),
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='content.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='practice_minimum',
            field=models.PositiveSmallIntegerField(default=5, help_text='Minimum exercises a student must complete before the test unlocks'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(help_text='Displayed on the Exerciții and Teste overview pages', max_length=200),
        ),
    ]
