# Generated by Django 5.1.6 on 2026-05-10 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0009_alter_lesson_options_remove_glossaryterm_lesson_and_more'),
        ('users', '0002_xp_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_kind', models.CharField(choices=[('pui_de_lup', 'Pui de lup')], help_text='Slug from apps.pets.species.PET_SPECIES.', max_length=50)),
                ('pet_xp', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(blank=True, default='', help_text='Optional custom name. Empty falls back to species default_name.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='content.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='users.studentprofile')),
            ],
            options={
                'db_table': 'pets',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'grade')},
            },
        ),
    ]
